### ISSUE TITLE
End of dialogs

### ISSUE THREAD

**Issue by aversluis1** [PerfectFit-project/testing-tickets#47] opened 2023-07-31 08:19 UTC
The exercise Ontspanning ends with a question, but if the user answers that they get the Sorry response with the menu. I think no dialog or exercise should end with a question if we don't want the user to type something. In this specific case I'd suggest to end the exercise by "Het is een goed idee om te bedenken hoe jij kunt ontspannen" and then a general "Dit is het einde van deze oefening" (which I'd like to include at the end of all exercises)

Tester: Eline

**Comment by wbaccinelli** [comment] 2023-07-31 11:45
Duplicate of https://github.com/PerfectFit-project/virtual-coach-issues/issues/406

**Closed as completed by wbaccinelli** 2023-07-31 11:45 UTC
